package sg.edu.nus.iss.spring_security_demo.entity;

import javax.persistence.*;

import lombok.Data;


@Entity
@Data

@Table(name="user")
public class User {

    // declare userId as primary key
    @Id
    // indicate primary key is generated by database, using auto increment
    @GeneratedValue (strategy = GenerationType.IDENTITY)
    private Long userId;
    private String firstName;
    private String lastName;
    private String password;
    private String email;
    private String role;
    private boolean enabled = false;
        
}

